### ISSUE TITLE
Update prisma peer dependency version to 5.0.0

### ISSUE THREAD

**Issue by revosw** [arthurfiorette/prisma-json-types-generator#113]

**Comment by arthurfiorette** [comment]
Need to test what was changed and what we need to test. Anyone open to start a PR?

**Comment by vimtor** [comment]
Maybe it helps, but I started getting these errors when running `prisma generate` after upgrading to `v5.0.0`:

```
✘ Type OfferWhereInput.shareClasses is not supported.
✘ Type OfferWhereInput.shareholderAgreementFiles is not supported.
✘ Type OfferScalarWhereWithAggregatesInput.shareClasses is not supported.
```

All of them are related to the annotation of the `Json` columns. For example given the following model:

```prisma
model Offer {
  id                        String                    @id @default(cuid())
  investorId                String
  investor                  Investor                  @relation(fields: [investorId], references: [id], onDelete: Cascade)
  companyId                 String
  company                   Company                   @relation(fields: [companyId], references: [id], onDelete: Cascade)
  /// [ShareClasses]
  shareClasses              Json?

  @@map("offers")
}
``` 

If I remove the `/// [ShareClasses]`, the first line of the error disappears. However, the types seem to be working.

**Comment by yeongjet** [comment]
very urgency.

**Comment by marcfalk** [comment]
+1 ✌️

**Comment by sreuter** [comment]
We're also running into this with our `Json` annotations.

**Comment by emroot** [comment]
Same here. Would love a pointer and I could work on a PR.

**Comment by camin-mccluskey** [comment]
Just to +1, seems like we're hitting the same issue when running `prisma generate` as a post install step during deployment
 
![Screenshot 2023-07-25 at 09 45 45](https://github.com/arthurfiorette/prisma-json-types-generator/assets/18604525/2842d230-0a45-44ad-8957-aaa6d7500564)

**Comment by livthomas** [comment]
Even though there were some warnings in the logs when using `prisma-json-types-generator` with Prisma 5.0.0, it still worked fine and all types we used were modified properly. However, after upgrading to Prisma 5.1.0, our custom types are no longer being applied. See https://github.com/arthurfiorette/prisma-json-types-generator/issues/122

**Comment by janpio** [comment]
I took a look at the failing tests and created a PR that makes them pass: https://github.com/arthurfiorette/prisma-json-types-generator/pull/128 (see with already run tests at https://github.com/prisma/prisma-json-types-generator/pull/2). See the PR text for more information.

**Comment by arthurfiorette** [comment]
Hey folks, sorry for the update delay, I'll be working on this later today/tomorrow. I'll close this issue in favor of #122.
