### ISSUE TITLE
Prisma 5.1.0 Support

### ISSUE THREAD

**Issue by cpojer** [arthurfiorette/prisma-json-types-generator#122]
It appears that Prisma 5.1.0 made various changes to type system, breaking prisma-json-types-generator completely.

See [Prisma 5.1.0 Release Notes](https://github.com/prisma/prisma/releases/tag/5.1.0).

It would be awesome to upgrade this project to support 5.1.0, or otherwise let the community know if this extension cannot be made work with 5.1.0.

**Comment by janpio** [comment]
Hm, that breakage was not intentional and is unexpected from our side, we did not take anything away so this should be fixable.
We're happy to help out here. Can someone please share the problems that are now popping up now?

**Comment by janpio** [comment]
I took a look at https://github.com/arthurfiorette/prisma-json-types-generator/issues/113 first and created a naive PR for that, see https://github.com/arthurfiorette/prisma-json-types-generator/issues/113#issuecomment-1666007054

**Comment by arthurfiorette** [comment]
> Hm, that breakage was not intentional and is unexpected from our side, we did not take anything away so this should be fixable. We're happy to help out here. Can someone please share the problems that are now popping up now?
> 
> Update: I guess the [test failures of the upgrade PR](https://github.com/arthurfiorette/prisma-json-types-generator/actions/runs/5752705319/job/15594288755?pr=124) is an indication what is broken?

Hey @janpio. No problem at all. I planned to fix some things and add support to prisma v5+ tomorrow morning...

> I took a look at https://github.com/arthurfiorette/prisma-json-types-generator/issues/113, the upgrade to Prisma 5.0.0, first and created a naive PR for that, see https://github.com/arthurfiorette/prisma-json-types-generator/issues/113#issuecomment-1666007054

>A PR upgrading from 5.0.0 to 5.1.1 still fails, but now with isolated errors caused by the type changes of Prisma 5.1.1: https://github.com/prisma/prisma-json-types-generator/actions/runs/5765346961/job/15631123039?pr=3

Thanks for also opening a PR! I'll look into it later this night.

**Comment by renatoaraujoc** [comment]
Hello,

I'm using Prisma v5.1.1 and I'm getting this output:

![Screenshot 2023-08-08 at 01 58 31](https://github.com/arthurfiorette/prisma-json-types-generator/assets/358128/126b4f57-a770-4e27-b2a0-c9fb81494f47)

The types are not being overwritten, they're still `JsonValue`:

![Screenshot 2023-08-08 at 02 00 21](https://github.com/arthurfiorette/prisma-json-types-generator/assets/358128/6beaf576-4eef-4220-bbb3-f8baec8d29cb)

This is my model:
![Screenshot 2023-08-08 at 02 01 14](https://github.com/arthurfiorette/prisma-json-types-generator/assets/358128/953a27f8-2768-4dea-b6be-99d31e2c9089)

**Comment by divyansh7924** [comment]
Same issue here with Prisma 5.1. Hope this resolves soon.

**Comment by janpio** [comment]
@renatoaraujoc Yes, this is the problem with 5.0 and 5.1 that is being tracked here. It currently does not work, and needs to be fixed to work again. @arthurfiorette is working on that right now.

**Comment by ymc9** [comment]
ZenStack also got broken in v5.1.1 because of the type renaming from `<Model>CountOutputTypeArgs` to `<Model>CountOutputTypeDefaultArgs`. Maybe it's the same issue?

https://github.com/zenstackhq/zenstack/issues/621

**Comment by arthurfiorette** [comment]
Progress being done at #128
