### ISSUE TITLE
Generated PrismaJson is empty

### ISSUE THREAD

**Issue by ArneCordes** [arthurfiorette/prisma-json-types-generator#143]
Running out of ideas how to get this to work. The generated namespace is empty:

**/node_modules/.prisma/client/index.d.ts**

```
// This file was overwritten by prisma-json-types-generator
// Report issues to

declare global {
  namespace PrismaJson {}
}
```

**prisma/schema.prisma**

```
generator client {
  provider = "prisma-client-js"
}

generator json {
  provider = "prisma-json-types-generator"
}

model Run {
  id           String    @id @default(cuid())
  status       RunStatus @default(CREATED)
  public_id    String
  project_name String?
  name         String?
  text         String?   @db.Text
  /// [RunAttributes]
  attributes   Json?
  project_id   String
  project      Project   @relation(references: [id], fields: [project_id])

  @@index([project_id])
}
```

**src/app.d.ts**

```
declare global {
  namespace PrismaJson {
    type RunAttributes = {
      address: string;
      location_type: string | null;
      location_type: "complex_estate" | "free_standing" | "plot_farm" | null;
      complex_name: string | null;
      unit_number: string | null;
      block_name: string | null;
      plot_farm_name: string | null;
      plot_farm_number: string | null;
      additional_notes: string | null;
    };
  }
}
```

```
"@prisma/client": "^5.1.1",
"prisma-json-types-generator": "^3.0.0-beta.4",
```

What am I missing? Thank you!

**Comment by arthurfiorette** [comment]
Hey @ArneCordes, the generated namespace should be empty. It is just a declaration to tell typescript that it its there. You now have to include your `src/app.d.ts` into your tsconfig to make the ts compiler join these two namespaces into one single type available everywhere.

You probably have something like `includes: ["src/**/*.ts"]` in your tsconfig which don't include your `src/app.d.ts` file.

**Comment by severoemanuel** [comment]
I just had the same problem in my new nest project, my prisma.d.ts is in the include array of tsconfig as well

**Comment by arthurfiorette** [comment]
`namespace PrismaJson {}` in `/node_modules/.prisma/client/index.d.ts` should always be empty. This isn't where the types are generated.

**Comment by arthurfiorette** [comment]
`PrismaJson` will always be empty. Definitions are imported from [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). which is done automatically by typescript. 

Make sure that your types are being included in your tsconfig/imported somewhere. You can test it out by renaming your `file.d.ts` to `file.ts` and see if anything changes.

**Comment by ArneCordes** [comment]
Just wanted to confirm that it works. I had to remove declare global around the namespace.. still new to TS :)

**Comment by dwheale-equi** [comment]
> Just wanted to confirm that it works. I had to remove `declare global` around the namespace.. still new to TS :)

This was exactly what I needed
