### ISSUE TITLE
Types are not replaced in generated files.

### ISSUE THREAD

**Issue by ness-IgorsShestiperov** [arthurfiorette/prisma-json-types-generator#166]
Hi,

I am using:

        "prisma": "^5.2.0",
        "prisma-json-types-generator": "^3.0.1",
        "typescript": "^5.2.2",

on mac. After build the result is still:

      /**
       * [VehicleLoanApplicationEntityPayload]
       */
      jsonData: Prisma.JsonValue

But that only happens on my machine. But other devs don't experience that issue. Maybe you have an idea of what can be the reason.

**Comment by arthurfiorette** [comment]
I do not know magic. Please try to provide a reproducible example or more information.

**Comment by ness-IgorsShestiperov** [comment]
Hi, 
I have found the problem. The bug is in source-path.ts:

`      return path.resolve(
        // Complete filename?
        clientOutput.match(/\.(d?\.?t|j|)sx?/g)
          ? // dirname
            path.dirname(clientOutput)
          : // filename
            clientOutput,
        'index.d.ts'
      );`

The path I have contains my name: /.../igors.shestiperov/.../

Regex is triggered and returns: Match: .s
clientOutput.match(/\.(d?\.?t|j|)sx?/g)

That result in wrong subfolder search : ../src/generated/prisma/index.d.ts'
instead of : ../src/generated/prisma/custom_folder

**Comment by arthurfiorette** [comment]
Thanks! I'll release a fix for it asap 👍🏻

**Comment by arthurfiorette** [comment]
Released in v3.0.2, would you mind trying it out?

**Comment by arthurfiorette** [comment]
Hey @ness-IgorsShestiperov I released v3.0.2, would you mind trying it out?

**Comment by ness-IgorsShestiperov** [comment]
It works now, thank you!
