### ISSUE TITLE
Couldn't find package "@prisma/generator-helper@5.4.1"

### ISSUE THREAD

**Issue by patrickkdev** [arthurfiorette/prisma-json-types-generator#174]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

3.0.2

### Description

I am trying to install with yarn add prisma-json-types-generator but I get the following error:

Couldn't find package "@prisma/generator-helper@5.4.1" required by "prisma-json-types-generator" on the "npm" registry.

I checked the internet connection and it is fine. I was able to install other packages.

### Steps to Reproduce

Just run yarn add prisma-json-types-generator

**Comment by arthurfiorette** [comment]
https://www.npmjs.com/package/@prisma/generator-helper/v/5.4.1

Something is wrong with your yarn setup. Have you cleared yarn cache?

**Comment by patrickkdev** [comment]
Hm, I will try that now

**Comment by patrickkdev** [comment]
Did not work

![Screenshot 2023-10-14 170229](https://github.com/arthurfiorette/prisma-json-types-generator/assets/115599753/3469dbb8-51ab-4212-84cf-a6c23ffb1641)

**Comment by arthurfiorette** [comment]
I'll close this issue as its not an issue with prisma-json-types-generator. I think this issue may help you: https://github.com/yarnpkg/yarn/issues/6029.
