### ISSUE TITLE
Issues with pushing new values to a JSON object array

### ISSUE THREAD

**Issue by Yarmeli** [arthurfiorette/prisma-json-types-generator#181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

"prisma": "^5.4.2",
"@prisma/client": "^5.4.2",
"prisma-json-types-generator": "^3.0.2",

### Description

Hey

I've been trying to add a simple JSON array to keep track of server logs on my Prisma Schema, but I keep getting the following TS error

```typescript
Type '{ push: { message: string; timestamp: string; }; }' is not assignable to type 'UpdateManyInput<ServerLog> | undefined'.
  Types of property 'push' are incompatible.
    Type '{ message: string; timestamp: string; }' is not assignable to type 'ServerLog[] | ((...items: ServerLog[]) => number) | undefined'.
      Object literal may only specify known properties, and 'message' does not exist in type 'ServerLog[] | ((...items: ServerLog[]) => number)'.ts(2322)
```

### Steps to Reproduce

This is my Prisma Schema:
```typescript
generator json {
    provider = "prisma-json-types-generator"
}
...

model MyModel {
...
    /// [ServerLog]
    logs  Json[]
...
}
```

And my `types.ts` file
```typescript
namespace PrismaJson {
  type ServerLog = {
    timestamp: string; // Date ISO
    message: string;
  };
}
```

The namespace and types are generated successfully, but it seems that pushing values into an array has the incorrect type.

The following code gives me the error:

```typescript
await ctx.prisma.mymodel.update({
  where: {
    id: input.id,
  },
  data: {
    logs: {
      push: {
        message: "My Message Here",
        timestamp: new Date().toISOString(),
      },
    },
  },
});
``` 

To "remove" the error, I need to push an array instead of a single value like this:
```typescript
await ctx.prisma.mymodel.update({
  where: {
    id: input.id,
  },
  data: {
    logs: {
     push: [
        {
          message: `My Message Here`,
          timestamp: new Date().toISOString(),
        },
      ],
    },
  },
});
``` 

### Expected Behavior

I should be able to push a single value, similar to [how scalar lists work in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-scalar-lists-arrays#adding-items-to-a-scalar-list)

**Comment by arthurfiorette** [comment]
Try putting it into a array. Prisma v5, if I'm not mistaken, only accepts arrays from now on.

**Comment by Yarmeli** [comment]
Putting into an array works but from my understanding, I should also be able to add a single value.

I experimented with a `String[]` instead of a `JSON[]` to see the current behavior for Prisma and it works as intended (i.e. I can push a single string instead of having to push a string array)
