### ISSUE TITLE
Inconsistent behavior when generating in parallel

### ISSUE THREAD

**Issue by jakeleventhal** [arthurfiorette/prisma-json-types-generator#193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

`prisma@5.3.0`
`prisma-json-types-generator@3.0.1`

### Description

I have a `prisma-generate` script in my package.json for 3 different prisma packages (each with different schemas/databases/etc.)

When I run `pnpm run -r prisma-generate`, it runs the generate script for all my database packages in parallel. Sometimes, it leads to issues where the custom types from `prisma-json-types-generator` don't get defined properly. It seems like there is some sort of collision/race condition going on here.

My suspicion is there is some shared resource that has a race condition.

### Steps to Reproduce

I described above, but it's kind of hard to reliably reproduce. I see this occur in CI like 5% of the time. The issue I get is something like:
```ts
// prismaJsonTypesNamespace.ts
interface MyCustomInterface {
  name: string
}
```
```prisma
/// [MyCustomInterface]
dataField  Json
```
Then my CI fails with some type error trying to access a property:
```ts
`name` does not exist on property `dataField`
```

### Expected Behavior

It doesn't do this.

**Comment by arthurfiorette** [comment]
Hi @jakeleventhal, thanks for this bug report! Can you attach a https://stackoverflow.com/help/minimal-reproducible-example or submit a PR containing the fix for it?

**Comment by jakeleventhal** [comment]
@arthurfiorette that is the problem. It isn't easy to reproduce and happens only rarely in CI. Are there any shared resources that might be used when generating types?

**Comment by arthurfiorette** [comment]
Nope, there's literally nothing that executes concurrently. Only a single file read is done when the generator is called by prisma and a single file write is done after everything was done. However, I think I've experienced this before, so I'll let this open for now.

**Comment by jakeleventhal** [comment]
I wasn't suggesting that this package is running logic in parallel. My question was whether or not this package uses some shared resource or temp directory or perhaps some singleton that might have race condition conflicts

**Comment by arthurfiorette** [comment]
Still no, it loads the `index.d.ts` into memory, changes it and flushes the memory into `index.d.ts` again. This is the entire generator core:

https://github.com/arthurfiorette/prisma-json-types-generator/blob/8ffcb2868ecfd01ce0799b1188496eeae60e9aeb/src/on-generate.ts#L26-L49

Line 26 reads, and 49 writes to disk, everything in between only changes the writer var which lives inside this function, not even global variables are used.

I'd love some help to reproduce this problem, until then I literally have no clue.

**Comment by jakeleventhal** [comment]
<img width="1062" alt="Screenshot 2023-11-18 at 2 40 02 PM" src="https://github.com/arthurfiorette/prisma-json-types-generator/assets/15133828/bcd2fb87-a24a-41d0-9d87-3f62c5701b11">
here is an example log when it breaks

**Comment by arthurfiorette** [comment]
@jakeleventhal can you also print the prisma generate logs step when the build fails?

**Comment by jakeleventhal** [comment]
```
. postinstall: packages/artelo/database prisma-generate$ prisma generate
. postinstall: packages/ecominate/database prisma-generate$ prisma generate
. postinstall: packages/ppc/database prisma-generate$ prisma generate
. postinstall: packages/artelo/database prisma-generate: Prisma schema loaded from prisma/schema.prisma
. postinstall: packages/ppc/database prisma-generate: Prisma schema loaded from prisma/schema.prisma
. postinstall: packages/ecominate/database prisma-generate: Prisma schema loaded from prisma/schema.prisma
. postinstall: packages/ppc/database prisma-generate: ✔ Generated Prisma Client (v5.6.0) to ./../../../node_modules/@prisma/client/ppc in 433ms
. postinstall: packages/ppc/database prisma-generate: ✔ Generated Prisma Json Types Generator (3.0.3) to ./prisma in 1.33s
. postinstall: packages/ppc/database prisma-generate: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
. postinstall: packages/ppc/database prisma-generate: ```
. postinstall: packages/ppc/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/ppc'
. postinstall: packages/ppc/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/ppc/database prisma-generate: ```
. postinstall: packages/ppc/database prisma-generate: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
. postinstall: packages/ppc/database prisma-generate: ```
. postinstall: packages/ppc/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/ppc/edge'
. postinstall: packages/ppc/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/ppc/database prisma-generate: ```
. postinstall: packages/ppc/database prisma-generate: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
. postinstall: packages/ppc/database prisma-generate: Done
. postinstall: packages/artelo/database prisma-generate: ✔ Generated Prisma Client (v5.6.0) to ./../../../node_modules/@prisma/client/artelo in 1.07s
. postinstall: packages/artelo/database prisma-generate: ✔ Generated Prisma Json Types Generator (3.0.3) to ./prisma in 2.64s
. postinstall: packages/artelo/database prisma-generate: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
. postinstall: packages/artelo/database prisma-generate: ```
. postinstall: packages/artelo/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/artelo'
. postinstall: packages/artelo/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/artelo/database prisma-generate: ```
. postinstall: packages/artelo/database prisma-generate: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
. postinstall: packages/artelo/database prisma-generate: ```
. postinstall: packages/artelo/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/artelo/edge'
. postinstall: packages/artelo/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/artelo/database prisma-generate: ```
. postinstall: packages/artelo/database prisma-generate: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
. postinstall: packages/artelo/database prisma-generate: Done
. postinstall: packages/ecominate/database prisma-generate: ✔ Generated Prisma Client (v5.6.0) to ./../../../node_modules/@prisma/client/ecominate in 1.14s
. postinstall: packages/ecominate/database prisma-generate: ✔ Generated Prisma Json Types Generator (3.0.3) to ./prisma in 2.15s
. postinstall: packages/ecominate/database prisma-generate: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
. postinstall: packages/ecominate/database prisma-generate: ```
. postinstall: packages/ecominate/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/ecominate'
. postinstall: packages/ecominate/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/ecominate/database prisma-generate: ```
. postinstall: packages/ecominate/database prisma-generate: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
. postinstall: packages/ecominate/database prisma-generate: ```
. postinstall: packages/ecominate/database prisma-generate: import { PrismaClient } from '../../../node_modules/@prisma/client/ecominate/edge'
. postinstall: packages/ecominate/database prisma-generate: const prisma = new PrismaClient()
. postinstall: packages/ecominate/database prisma-generate: ```
. postinstall: packages/ecominate/database prisma-generate: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
. postinstall: packages/ecominate/database prisma-generate: Done
. postinstall: Done
```

**Comment by arthurfiorette** [comment]
Hey @jakeleventhal, this problem appeared after some time of 3.0.1 released, and it's not happening to us anymore. I'm pretty sure it was an issue with prisma itself. Can you confirm this still happens?

**Comment by jakeleventhal** [comment]
This definitely still happens all the time.

**Comment by arthurfiorette** [comment]
I cannot reproduce it yet... Would you mind taking your time and trying to create a reproducible repository?

**Comment by jakeleventhal** [comment]
I would, but I'm actively in the process of migrating to drizzle. Too many papercuts in prisma. Feel free to close this, or leave it open.

**Comment by arthurfiorette** [comment]
It's funny because we're also doing this migration 😅😁
