### ISSUE TITLE
feat: add `output` param in the `generator`

### ISSUE THREAD

**Issue by 413n** [arthurfiorette/prisma-json-types-generator#2]
I'm using `pnpm` with `turborepo` in my project and I have a `prisma` dedicated package.
Unfortunately when I try to generate the schema, the client is generated like this: `✔ Generated Prisma Client (4.8.0 | library) to .\..\..\node_modules\.pnpm\@prisma+client@4.8.0_prisma@4.8.0\node_modules\@prisma\client in 278ms`

Instead, looking at the code of this lib, it always search for `.prisma/client` in the current node_modules directory.

Could you please add the `output` param in the `generator` so that we can change the path of the generated client?

Oh and btw, amazing lib! Great work!

**Comment by emroot** [comment]
👍

**Comment by arthurfiorette** [comment]
Hey, sorry for the delay.
Anyone up to a PR here?
This week I won't have any spare time for it...

**Comment by arthurfiorette** [comment]
Hey, just released `1.1.0` with the required change. Can you guys test it out?

**Comment by 413n** [comment]
Hey @arthurfiorette, thanks for the work! Unfortunately there is an error.
I already debugged it and basically inside ´on-generate´ you try to get the ´output´ from ´options.generator.config.output´ (on line 13) but it's always undefined. Instead you should get the output param from ´options.generator.output.value´. Changing that, the path works correctly!
I will open a PR for that

**Comment by arthurfiorette** [comment]
Hey, `1.1.2` came with a breaking change for you, stay up with it at #7 :)

**Comment by arthurfiorette** [comment]
Hey @413n, `1.1.2` came with a breaking change for you, stay up with it at #7 :)
