### ISSUE TITLE
Document when `declare global` is needed

### ISSUE THREAD

**Issue by Stadly** [arthurfiorette/prisma-json-types-generator#212]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

3.0.3

### A minimal reproducible example

N/A

### Description

[Some users report](https://github.com/arthurfiorette/prisma-json-types-generator/issues/143#issuecomment-1738747314) that they must remove `declare global` from the `types.ts` file in order to make the JSON types work with Prisma. I also experienced this.

Do we know in which cases `declare global` is needed and not? Can it be documented in the `README`?

### Steps to Reproduce

N/A

**Comment by arthurfiorette** [comment]
Hey @Stadly, can you provide your `tsconfig.json`? I do not know why you had to remove it, but its probably related to a tsconfig setting.

**Comment by Stadly** [comment]
Hi @arthurfiorette, thanks for the quick response!

I'm using SvelteKit, so I have two `tsconfig.json` files:

```json
// tsconfig.json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "exactOptionalPropertyTypes": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "outDir": "build",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true
  }
  // Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
  //
  // If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
  // from the referenced tsconfig.json - TypeScript does not merge them in
}
```

```json
// .svelte-kit/tsconfig.json
{
	"compilerOptions": {
		"paths": {
			"$lib": [
				"../src/lib"
			],
			"$lib/*": [
				"../src/lib/*"
			]
		},
		"rootDirs": [
			"..",
			"./types"
		],
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true,
		"lib": [
			"esnext",
			"DOM",
			"DOM.Iterable"
		],
		"moduleResolution": "node",
		"module": "esnext",
		"target": "esnext",
		"ignoreDeprecations": "5.0"
	},
	"include": [
		"ambient.d.ts",
		"./types/**/$types.d.ts",
		"../vite.config.ts",
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte",
		"../tests/**/*.js",
		"../tests/**/*.ts",
		"../tests/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"./[!ambient.d.ts]**",
		"../src/service-worker.js",
		"../src/service-worker.ts",
		"../src/service-worker.d.ts"
	]
}
```

**Comment by arthurfiorette** [comment]
https://github.com/arthurfiorette/prisma-json-types-generator?tab=readme-ov-file#declare-global-is-not-working
