### ISSUE TITLE
untyped fields used to be Prisma.JsonValue and now are unknown

### ISSUE THREAD

**Issue by shawnjones253** [arthurfiorette/prisma-json-types-generator#219]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

```
"prisma-json-types-generator": "3.0.3",
"@prisma/client": "5.4.2",
"prisma": "5.4.2",
```

### A minimal reproducible example

n/a

### Description

In previous versions of this plugin, untyped fields would be left alone (as if the plugin wasn't used), which meant they would be of type `Prisma.JsonValue`, in the current version the choice seems to be between `unknown` and `any`.

Is there any option to type the fields which have the necessary triple-slash comment, but let prisma use its default `Prisma.JsonValue` for the fields which don't?

### Steps to Reproduce

in schema:

```
model TestModel {
  untypedJson: Json
  /// [MyJsonType]
  typedJson: Json
}
```

and in code:
```
declare global {
  namespace PrismaJson {
    type MyJsonType = { foo: string }
  }
}
```

generated prisma client:
```
untypedJson: unknown
typedJson: MyJsonType
```

### Expected Behavior

I'd prefer the following if possible:

generated prisma client:
```
untypedJson: Prisma.JsonValue
typedJson: MyJsonType
```

**Comment by shawnjones253** [comment]
I've used the following as a workaround:

code
```
declare global {
  namespace PrismaJson {
    type PrismaJsonValue = Prisma.JsonValue
  }
}
```

schema
```
/// [PrismaJsonValue]
untypedJson Json
```

**Comment by arthurfiorette** [comment]
As clearly stated in the documentation, use `allowAny = true`.

![image](https://github.com/arthurfiorette/prisma-json-types-generator/assets/47537704/e1a440fa-f41f-4373-9872-f539a678b529)

**Comment by shawnjones253** [comment]
i don't want `any`, i want `Prisma.JsonValue`

**Comment by arthurfiorette** [comment]
`Prisma.JsonValue` is almost any, thus the easier to understand name.
