### ISSUE TITLE
Cannot install in npm project, forcing pnpm

### ISSUE THREAD

**Issue by Noitidart** [arthurfiorette/prisma-json-types-generator#23]
Thanks for helping solve such a issue with Prisma!

I am using npm in my project. I didnt want to add another dep manager.

Doing `npm i prisma-json-types-generator` causes this error and fails to install:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/6372489/219977331-ae83561d-2a0a-4e9a-b815-0b346c6c8a84.png">

**Comment by arthurfiorette** [comment]
Lol, I added this thinking it would only affect development.
Releasing 2.2.3 now...

**Comment by Noitidart** [comment]
Thank you so much! For such speed. Sincerely appreciate it!!

**Comment by Noitidart** [comment]
Hey hey sorry about the bump, I ninja edited my last comment lol. Is it safe to `npm i -D`?

**Comment by arthurfiorette** [comment]
Yes! This is intended to be ran only in development.

**Comment by Noitidart** [comment]
Thanks very much brother!
