### ISSUE TITLE
npm Docs Overwritten by New Version

### ISSUE THREAD

**Issue by arimgibson** [arthurfiorette/prisma-json-types-generator#257]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

3.0.4
3.0.3

### A minimal reproducible example

N/A

### Description

Not a bug of the package per say, but the npm page had a bunch of documentation last night. It seems to have been overwritten by the README.md when the package was updated this morning. Thought I was going crazy :laughing: 

Package page for v3.0.3 release
![image](https://github.com/arthurfiorette/prisma-json-types-generator/assets/43756494/f061734c-2415-4153-ae7d-669ebbd6a8ba)
https://www.npmjs.com/package/prisma-json-types-generator/v/3.0.3

Package page for latest (v3.0.4) release
![image](https://github.com/arthurfiorette/prisma-json-types-generator/assets/43756494/89ef0a29-7052-4bde-942e-60439744cb69)
https://www.npmjs.com/package/prisma-json-types-generator

The documentation in the README is much less complete -- in my opinion, the README should contain all information previously shown on the npm page as well. I'm happy to PR this

### Steps to Reproduce

1. Visit [documentation page from v3.0.3](https://www.npmjs.com/package/prisma-json-types-generator/v/3.0.3)
2. Visit [documentation page for latest](https://www.npmjs.com/package/prisma-json-types-generator)
3. Observe major differences in content, including lots of key information missing

### Expected Behavior

Documentation should not update unless the README.md file is updated. README.md should contain the same information as the npm package page -- including complete documention unless an external documentation website is used.

**Comment by arthurfiorette** [comment]
Weird... Thanks for pointing this out!

Are you up to a PR?

**Comment by arimgibson** [comment]
> Weird... Thanks for pointing this out!
> 
> Are you up to a PR?

Yep! Should have time over this weekend :smile:

**Comment by arimgibson** [comment]
Sorry for the super late follow up @arthurfiorette -- looks like you updated the README with https://github.com/arthurfiorette/prisma-json-types-generator/commit/e75de39a3be80ac9a3b8199e311afd53011ad971 and then deploying the v3.0.4 package caused it to update on npm as well.

I'm starting work on a PR to include some of the information from the old README, which will be opinionated for what information I thought helped me. Obviously feel free to remove whatever is no longer relevant or helpful :relaxed:

**Comment by arthurfiorette** [comment]
https://github.com/arthurfiorette/prisma-json-types-generator/releases/tag/v3.1.0
