### ISSUE TITLE
Does triple slash have significance?

### ISSUE THREAD

**Issue by Noitidart** [arthurfiorette/prisma-json-types-generator#26]
I'm not sure, but I think if I'm not using triple slash, my prisma types are not correct when running `npx prisma generate`. I added triple slash and it worked.

Does the:

```
declare global {
  namespace PrismaJson {
```

have to go into a `.d.ts` file so it gets loaded in order to work? My tsconfig is this:

```
"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
```

So I thought it would read all the types even if I place it in a rnadom `.ts` file that no one imports.

**Comment by arthurfiorette** [comment]
Triple slash is the correct way of documenting things in a prisma schema files.

https://www.prisma.io/docs/concepts/components/prisma-schema#comments

**Comment by Noitidart** [comment]
Oooh! Thank you!

**Comment by Noitidart** [comment]
Ahhh! Thank you! Should these also be triple or is it ok to make these double?

```

// Always after the prisma-client-js generator
generator json {
  provider = "prisma-json-types-generator"
  // namespace = "PrismaJson"
  // clientOutput = "<finds it automatically>"
  // (./ -> relative to schema, or an importable path to require() it)
}
```

**Comment by arthurfiorette** [comment]
these weren't meant to be "jsdoc" comments, just are examples in the readme :)

**Comment by Noitidart** [comment]
Ah got it, thank you very much!
