### ISSUE TITLE
Array syntax missing bracket

### ISSUE THREAD

**Issue by Noitidart** [arthurfiorette/prisma-json-types-generator#29]
Hi there, after doing generate, I'm seeing it's missing the 2nd bracket for the array, is this an issue?

<img width="313" alt="image" src="https://user-images.githubusercontent.com/6372489/222500471-fa91290c-1a10-4442-a00a-592904ff9548.png">

My schema looks like:

```
  /// [TSlide[]]
  slides                  Json?
```

And I define this like this:

```

declare global {
  namespace PrismaJson {
    type TSlide = {
      photo: string;
      hidden?: boolean;
      widgetable?: boolean;
      slideshowable?: boolean;
    };
  }
}
```

**Comment by arthurfiorette** [comment]
Nullable arrays aren't even available in prisma yet. You shall use `[]` instead of `null`.

```prisma
model Test {
  /// [TSlide]
  slides                  Json[]
}
```

**Comment by Noitidart** [comment]
Thanks for fast reply!

What I did was kept:

```
model Test {
  /// [TSlides]
  slides        Json
}
```

Then my typescript I made it:

```
declare global {
  namespace PrismaJson {
    type TSlides = {
      photo: string;
      hidden?: boolean;
      unwidgeted?: boolean;
      unslideshowed?: boolean;
    }[];
  }
}
```
