### ISSUE TITLE
Json types inside type declarations won't work

### ISSUE THREAD

**Issue by thomasbouillon** [arthurfiorette/prisma-json-types-generator#303]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

v3.0.4

### A minimal reproducible example

https://github.com/thomasbouillon/reproduce-prisma-json-issue

### Description

The README says `Json types inside type declarations won't work` but the linked issue has been resolved and merged since prisma 4.16.0.

Now it should work ?

(using mongodb if that changes anything)

### Steps to Reproduce

`schema.prisma`
```prisma
model A {
    nested B
}

type B {
   /// [CustomJson]
   myJsonValue Json
}
```

```bash
yarn prisma generate
```

Result:
```ts
... 
{
       /**
       * [CustomJson]
       */
      myJsonValue: Prisma.JsonValue
}
```

### Expected Behavior

`schema.prisma`
```prisma
model A {
    nested B
}

type B {
   /// [CustomJson]
   myJsonValue Json
}
```

```bash
yarn prisma generate
```

Result:
```ts
... {
       /**
       * [CustomJson]
       */
      myJsonValue: PrismaJson.CustomJson  //  <-----
}
```

**Comment by arthurfiorette** [comment]
Hey @thomasbouillon, thanks for this bug report. Since then I didn't implemented and/or testes support for json inside prisma types. Are you open to PR it? remember to add unit tests...
