### ISSUE TITLE
Support for generating string discriminated unions

### ISSUE THREAD

**Issue by noahsark769** [arthurfiorette/prisma-json-types-generator#34]
Hey @arthurfiorette thank you for the awesome utility here! We're planning on using it at [Replo](https://replo.app) to auto-generate types for the json models in our database. I was wondering if you'd be willing to accept a PR which implemented support for discriminated unions of strings as well as json (happy to help with the implementation if you can point me to the right place). Our use case is:

```ts
// schema.prisma
model MyModel {
    /// [ModelKind]
    kind                          String?          @db.VarChar(512)
    // ...
}

// index.ts
declare global {
  namespace PrismaJson {
    // ...
    type ModelKind =
      | "page"
      | "article"
      | "section";
  }
}
```

Ideally, we'd like the generated client to have all MyModel operations return types have the `kind` be typed as the ModelKind DU. Currently, this gives [this not supported error](https://github.com/arthurfiorette/prisma-json-types-generator/blob/426956ece836e0a31e41bba8e13bb3f24a374ae7/src/helpers/handle-signature.ts#L94), so I assume supporting this would involve handing the String type correctly there and outputting the alias.

Let me know what you think! If you're down to accept something like this, let me know if that implementation seems correct and we can start working on a prototype 👍

**Comment by arthurfiorette** [comment]
Hi @noahsark769, awesome idea! I'd love to implement it!

**Comment by arthurfiorette** [comment]
You'd probably start by changing some Ifs that filters out non `Json` field types, and then adding your case to [this function](https://github.com/arthurfiorette/prisma-json-types-generator/blob/010bc53e2ac7f7b7f44768a57a0ddbadefb26a0c/src/helpers/handle-signature.ts#L8).

But, I think a new syntax for string literals or even some checks should be made to prevent you assign a non string literal type to a string, which will only throw an error at runtime.

As you can see, the replace signature handle all variations a field can have, Like `User`, `Prisma.UserFindManyArgs` and so on. If you get some complex fields, like `StringFilter`, using a more generic approach should do the job. (Like the [`Update<T>`](https://github.com/arthurfiorette/prisma-json-types-generator/blob/010bc53e2ac7f7b7f44768a57a0ddbadefb26a0c/src/helpers/namespace.ts#L22) generated type and its [usage](https://github.com/arthurfiorette/prisma-json-types-generator/blob/010bc53e2ac7f7b7f44768a57a0ddbadefb26a0c/src/helpers/handle-signature.ts#L8))

I'm currently moving to another state, but i'll try to merge it asap. :)

**Comment by noahsark769** [comment]
Alright, started on a draft PR at #39, managed to get local development set up and tests passing for the simple string case, will work on implementing support for more complex filter types and unions soon!
