### ISSUE TITLE
Local development: running `pnpm test` results in "prisma-json-types-generator: command not found"

### ISSUE THREAD

**Issue by noahsark769** [arthurfiorette/prisma-json-types-generator#38]
While working on #34, I was trying to set up local development for the package and noticed that there was a test command. However, running `pnpm build` then `pnpm test` gives the following error for me:

```
$ pnpm test

> prisma-json-types-generator@2.2.3 test /Users/noahgilmore/code/prisma-json-types-generator
> prisma generate && tsc --noEmit -p tsconfig.test.json

Prisma schema loaded from prisma/schema.prisma
Error: Generator at prisma-json-types-generator could not start:

/bin/sh: prisma-json-types-generator: command not found

 ELIFECYCLE  Test failed. See above for more details.
```

I'm assuming that this is because we specified the generator as `prisma-json-types-generator` in `schema.prisma`, but prisma doesn't know how to find an executable called that name. I've never worked with a custom prisma generator before, but assuming I'm missing a step somewhere? If so, would be happy to document it! Tagging @arthurfiorette since I'm assuming you had a different workflow for when you added these tests.

**Comment by noahsark769** [comment]
I was able to get local tests running by subbing in the following in schema.prisma:

```
generator json {
  provider = "node ./dist/generator.js"
}
```

Not sure if that's the recommended way, but happy to document it if it is!

**Comment by noahsark769** [comment]
There may be another issue here: running `npm install && npm build && npm test` works correctly with the above modification to the `generator json`, but `pnpm install && pnpm build && pnpm test` does not - something about typescript not being able to find the generated @prisma/client package correctly with pnpm's install location

**Comment by arthurfiorette** [comment]
> I was able to get local tests running by subbing in the following in schema.prisma:
> 
> ```
> generator json {
>   provider = "node ./dist/generator.js"
> }
> ```
> 
> Not sure if that's the recommended way, but happy to document it if it is!

I was previously using `npm link` and `npm install -g` on my local setup.

**Comment by arthurfiorette** [comment]
> but pnpm install && pnpm build && pnpm test does not

I'll investigate it

**Comment by arthurfiorette** [comment]
e8e49795069d175d8da55c37efbe3d2e7026a4b9 fixes this.
