### ISSUE TITLE
Type recognized but runtime parsing does not yield the type.

### ISSUE THREAD

**Issue by pauldesmondparker** [arthurfiorette/prisma-json-types-generator#401]
Raising this issue as documentation, in case it helps someone else in the future.

My LSP was recognizing my prisma field as the type I declared, but at runtime it was still a string.

My relevant `schema.prisma`:
```prisma
generator client {
  provider = "prisma-client-js"
}

generator json {
  provider = "prisma-json-types-generator"
  allowAny = true
}

// ...

model rfq {
  id: ...
  /// ![{lat: number; lng: number }]
  geo_point: Json
}
```
This was producing the desired result in my LSP.
![image](https://github.com/user-attachments/assets/6ee5b72d-572d-44bc-bced-0683e673a9e9)

However, due to a mistake whereby I was still seeding the database with records saved with output from `JSON.stringify`, the whole process seemed to be short-circuited for the tests (vitest) that I was running.

The resolution was to apply the `{lat: 22.2344, lng: 103.2564}` object directly to the `geo_point` field in the seed.

**Comment by arthurfiorette** [comment]
Hi! I'd love if you could open a PR to document it <3

**Comment by pauldesmondparker** [comment]
I'm not sure that it deserves documentation. This is a case of me abusing the usage of `Prisma`.  Writes are done with objects that conform to `Prisma.JsonValue`, and typescript will emit an error if it does not. However, I was passing in a string (the stringified object) and that technically conforms ([RFC7159](http://www.ietf.org/rfc/rfc7159.txt)).

This issue is just for anyone else who happens to implement this particular comedy of errors.
