### ISSUE TITLE
Discrimination by model value?

### ISSUE THREAD

**Issue by saschagehlich** [arthurfiorette/prisma-json-types-generator#409]
Hey, let's say I have the following model: 

```prisma
model Vehicle {
  type VehicleType
  settings Json @default({})
}

enum VehicleType {
  CAR
  BIKE
  BICYCLE
  QUAD
}
```

And my `settings` column might have different JSON data depending on `type`. Is there any way to have `type` as the discriminator?

**Comment by arthurfiorette** [comment]
I don't think this is possible because it would require us to make `Vehicle` type have a generic parameter in the dts file:

```ts
export type Vehicle<T extends VehicleType> {
  type: T;
  settings: T extends VehicleType.CAR ? ...
}
```

**Comment by arthurfiorette** [comment]
closing this until further solution is available
