### ISSUE TITLE
Array types not supported; types with `]` leads to a syntax error

### ISSUE THREAD

**Issue by qwaz-theori** [arthurfiorette/prisma-json-types-generator#412]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

v3.1.1

### A minimal reproducible example

.

### Description

Running the generator with types that include `]` as part of their name generates a type definition file with a syntax error. The brackets are not properly closed.

### Steps to Reproduce

```prisma
model URL {
  /// ![[string, string][]]
  queryParams Json
}
```

Type definition generated for this definition contains the following field:
```typescript
queryParams: ([string, string)
```

Note that the bracket is not properly closed.

### Expected Behavior

This is likely caused by a non-greedy matching in the type regex. Removing the `?` mark in `.*?` will likely fix the problem.

https://github.com/arthurfiorette/prisma-json-types-generator/blob/869a559c22b868227db1a753ef948498697d749c/src/helpers/regex.ts#L6

Before: https://regexr.com/883c6
After: https://regexr.com/883c9

As a workaround, it is possible to define the array type directly into `PrismaJson` namespace.
```
// schema.prisma
model URL {
  /// ![KeyValueArray]
  queryParams Json
}

// TypeScript
declare global {
  namespace PrismaJson {
    type KeyValueArray = [string, string][];
  }
}
```

**Comment by arthurfiorette** [comment]
Hmm, I don't think this will be possible to solve with regexes. Any ideas?

**Comment by arthurfiorette** [comment]
![image](https://github.com/user-attachments/assets/cd315205-8ab6-42a8-977b-dc8ebb0a4f55)
