### ISSUE TITLE
Library isn't working for me

### ISSUE THREAD

**Issue by psecuresystem** [arthurfiorette/prisma-json-types-generator#45]
My file structure:
prisma
  - schema.prisma
src
  - jsonTypes.ts(the types that I'm using)
 
My schema.prisma file
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions", "fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator json {
  provider  = "prisma-json-types-generator"
  namespace = "PrismaJsonTypes"
}

model AppData {
  /// [One of my types]
  aField Json?
}

// My other db schema
```

My jsonTypes.ts
```js
declare global {
  namespace PrismaJsonTypes {
    // My types
  }
}
```

When I use prisma to fetch the data, the `aField` type is any(not `Prisma.JsonValue`). After inspecting I realised that prisma isn't finding my namespace.

**Comment by psecuresystem** [comment]
Really sorry can you please help me. Was supposed to integrate this into production.

**Comment by arthurfiorette** [comment]
Can you provide a more detailed example? Like, what is in the dts structure `prisma-json-types-generator` was supposed to modify?

**Comment by psecuresystem** [comment]
Sorry found my issue

**Comment by arthurfiorette** [comment]
Hey @psecuresystem, don't be this kind of guy, share you solution here to save others people time too!

**Comment by psecuresystem** [comment]
Sorry. It turns out I didn't import `prisma-json-types-generator`
