### ISSUE TITLE
pnpm monorepo path issue

### ISSUE THREAD

**Issue by jakeleventhal** [arthurfiorette/prisma-json-types-generator#55]
https://github.com/arthurfiorette/prisma-json-types-generator/blob/8e5ca7c3f4095fe005429f3a414da420919af025/src/file/source-path.ts#L28

When running the generate command, i get this error
```
Prisma schema loaded from ../../packages/pl-database/prisma/schema.prisma
Error: 
Cannot find module '/Users/jakeleventhal/Code/Ecominate/packages/.prisma/client'
```

The path that it should be looking in is wrong.
My schema file has this
```
generator client {
  provider        = "prisma-client-js"
  output          = "./"
  previewFeatures = ["clientExtensions", "fullTextSearch", "fullTextIndex"]
}
```
If i remove this line
```
output          = "./"
```
it works just fine

**Comment by arthurfiorette** [comment]
That's correct, because `./` is not the same path as the one we automatically find for you. The output, as the doc ways, should be the same as where prisma client generates its outputs.
