### ISSUE TITLE
fix: types are not replace using ´pnpm´

### ISSUE THREAD

**Issue by 413n** [arthurfiorette/prisma-json-types-generator#6]
When using ´pnpm´, the types are not replaced with the correct namespace in the ´.prisma/client/index.d.ts´ file.
They remains as ´Prisma.JsonValue´.

Using ´yarn´ it works fine.

**Comment by arthurfiorette** [comment]
But is the prisma client being emmited to `.prisma/client/index.d.ts` when using pnpm?

**Comment by arthurfiorette** [comment]
and what do you mean by using `yarn` and `pnpm` with this package? This package is a prisma generator.

**Comment by 413n** [comment]
For some reasons when using `pnpm` the types were not replaced in the `.prisma/client/index.d.ts`. Luckly now it seems to work with the latest release (`1.1.2`). Thanks for your work!
