### ISSUE TITLE
Can't set `clientOuput` with an environment variable

### ISSUE THREAD

**Issue by abonifacio** [arthurfiorette/prisma-json-types-generator#60]
Hi! First of all, thanks for making this patch available.

I have not so common requirement (I assume), which is setting prisma's output directory through an environment variable. e.g.

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = env("PRISMA_OUT_DIR")
  binaryTargets = ["native", "linux-musl"]
}
```

When I don't define `clientOuput` it fallbacks to `.prisma/client`

```prisma
generator json {
  provider     = "prisma-json-types-generator"
}
```

```
Error: 
✔ Generated Prisma Client (4.7.1 | library) to ./apps/payments/node_modules/prisma-generated in 267ms
Cannot find module '/path/to/repo/apps/payments/.prisma/client'
Require stack:
```

When I define `clientOutput` as `env("PRISMA_OUT_DIR")` it looks like it doesn't evaluate the function

```prisma
generator json {
  provider     = "prisma-json-types-generator"
  clientOutput        = env("PRISMA_OUT_DIR")
}
```

```
Error: 
✔ Generated Prisma Client (4.7.1 | library) to ./apps/payments/node_modules/prisma-generated in 259ms
ENOENT: no such file or directory, open '/path/to/repo/apps/payments/prisma/(function)/index.d.ts'
```

Finally if I harcode the same value as `PRISMA_OUT_DIR` it works

```prisma
generator json {
  provider     = "prisma-json-types-generator"
  clientOutput = "../node_modules/prisma-generated"
}
```

Unfortunately I need the output to be set dynamically through the aforementioned variable. Any chance this is an easy fix?

**Comment by arthurfiorette** [comment]
Hey @abonifacio, this seems like a very good feature, you're up to a PR?

**Comment by arthurfiorette** [comment]
Update: prisma does not support it for now. See https://github.com/prisma/prisma/issues/19065

**Comment by arthurfiorette** [comment]
This is a well known issue since 2021. I wouldn't get high hopes on it being implemented.
https://github.com/prisma/prisma/issues/8990

**Comment by arthurfiorette** [comment]
What I could do, if you really need this issue and don't have any workarounds, is to add a string syntax like `::OUTPUT` to this generator itself try to resolve from env.

**Comment by abonifacio** [comment]
Hi @arthurfiorette thanks for looking into this, in my case I ended up casting the types for now 🤷🏽‍♂️ . I appreciate the goodwill but I think this should be fixed by Prisma
