### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by mankinchi** [arthurfiorette/prisma-json-types-generator#62]
Hi, I have spent an hour trying to figure this out but still can't understand how it should work.

I have this schema
```
generator client {
  provider = "prisma-client-js"
}

generator json {
  provider = "prisma-json-types-generator"
}

model UserHouseInfo {
  id     Int  @id @default(autoincrement())
  userId Int
  user   User @relation(fields: [userId], references: [id])
  /// [HouseInfo]
  info   Json

  @@index([userId])
}
```

and then generate. I will only have this 
```
declare global {
  namespace PrismaJson {}
}

export type UserHouseInfo = {
  id: number
  userId: number
  /**
   * [HouseInfo]
   */
  info: PrismaJson.HouseInfo
}
```

where PrismaJson.HouseInfo is just any.

I have another type file that include HouseInfo like this 
```
export type HouseInfo = {
	name: string;
	address: string;
};
```

but I'm uncertain how it's linked together. Can someone walk me through it? Or update the readme for better steps? Thanks :)

**Comment by arthurfiorette** [comment]
Hi @mankinchi, you have to declare your own `PrismaJson` too with your type within your source files. I do not recommend messing and/or changing the generated file.

```ts
// src/index.ts
 
declare global {
 export type HouseInfo = {  
    name: string;
    address: string;
  };
}
```

**This is explicitly shown in the first readme example:**

![image](https://user-images.githubusercontent.com/47537704/235474200-2d5dab58-2699-466a-a3d8-31e3b4e07a22.png)
