### ISSUE TITLE
Add option to use type instead of namespace

### ISSUE THREAD

**Issue by Arlen22** [arthurfiorette/prisma-json-types-generator#64]
It would be very useful if there was a generator option to emit `PrismaJson["MyType"]` instead of `PrismaJson.MyType`, unless I'm missing something. This would allow me to do something like 

```ts
  export type PrismaJson ={ [K in keyof Types]: ValueTree<Types[K]> };
```

**Comment by arthurfiorette** [comment]
What would be the usage of it?

May I ask why you need to write:

```ts
declare global {
  export type X = ...
}
```

?

**Comment by Arlen22** [comment]
I'm generating the schema from Typescript and so I just need a mapped type to get the field types.

**Comment by arthurfiorette** [comment]
Well, this should be very straightforward to implement, you're up to do a PR?

**Comment by arthurfiorette** [comment]
I'll work on this asap

**Comment by vabatta** [comment]
Do you have an example anywhere on how to make this work? 
I simply want everything that is not typed to inherit `JsonValue` from `type-fest`.
