### ISSUE TITLE
"Cannot find module" without `outputs` generator config

### ISSUE THREAD

**Issue by JayNakrani** [arthurfiorette/prisma-json-types-generator#7]
Hey Arthur,

First off, thank you so much for the generator. It's a game-changer!

I tried using this in my personal Prisma + NextJS project but ran into a `Cannot find module '/<PROJECT_ROOT_PATH>/prisma'` error. 

The following snippet assumes that when `outputs` is not specified in the generator config, then `options.generator.output?.value` will be `undefined`. However, in my case, even though I am not specifying `outputs` in generator config, the value of `overrideTarget` or `options.generator.output?.value` is `"/<PROJECT_ROOT_PATH>/prisma"`

https://github.com/arthurfiorette/prisma-json-types-generator/blob/6c1505bafb5a1ed79b689eabfb76e3cf2637f3ed/src/file/reader.ts#L25-L33

I console-logged the `options` object from [`onGenerate()`](https://github.com/arthurfiorette/prisma-json-types-generator/blob/6c1505bafb5a1ed79b689eabfb76e3cf2637f3ed/src/on-generate.ts#L10) and below is the full output.

```shell
$ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
options.generator =  {
  "name": "json_gen",
  "provider": {
    "fromEnvVar": null,
    "value": "prisma-json-types-generator"
  },
  "output": {
    "value": "/<PROJECT_ROOT_PATH>/prisma",
    "fromEnvVar": "null"
  },
  "config": {
    "namespace": "IO"
  },
  "binaryTargets": [],
  "previewFeatures": []
}
Error: 
✔ Generated Prisma Client (4.8.1 | library) to ./node_modules/@prisma/client in 148ms

Cannot find module '/<PROJECT_ROOT_PATH>/prisma'
Require stack:
- /<PROJECT_ROOT_PATH>/node_modules/prisma-json-types-generator/dist/file/reader.js
- /<PROJECT_ROOT_PATH>/node_modules/prisma-json-types-generator/dist/on-generate.js
- /<PROJECT_ROOT_PATH>/node_modules/prisma-json-types-generator/dist/generator.js
- /<PROJECT_ROOT_PATH>/node_modules/prisma-json-types-generator/dist/bin.js
```

When I hardcode the `output = "/<PROJECT_ROOT_PATH>/node_modules/.prisma/client/index.d.ts"`, then everything works -- it essentially forces [this execution branch](https://github.com/arthurfiorette/prisma-json-types-generator/blob/6c1505bafb5a1ed79b689eabfb76e3cf2637f3ed/src/file/reader.ts#L27)

### OS & Package Versions

```shell

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy


$ yarn list --pattern prisma prisma-json-types-generator
yarn list v1.22.19
├─ @prisma/client@4.8.1
├─ @prisma/debug@4.0.0
├─ @prisma/engine-core@4.0.0
├─ @prisma/engines-version@4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
├─ @prisma/engines@3.16.0-49.da41d2bb3406da22087b849f0e911199ba4fbf11
├─ @prisma/fetch-engine@3.16.0-49.da41d2bb3406da22087b849f0e911199ba4fbf11
│  └─ @prisma/debug@3.15.2
├─ @prisma/generator-helper@4.0.0
├─ @prisma/get-platform@3.16.0-49.da41d2bb3406da22087b849f0e911199ba4fbf11
│  └─ @prisma/debug@3.15.2
├─ @prisma/sdk@4.0.0
├─ prisma-json-types-generator@1.1.1
│  ├─ @prisma/debug@4.8.1
│  └─ @prisma/generator-helper@4.8.1
└─ prisma@4.8.1
   └─ @prisma/engines@4.8.1
```

### JSON Type Generator setup

```
// /<PROJECT_ROOT_PATH>/prisma/schema.prisma

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

generator json_gen {
  provider = "prisma-json-types-generator"
  namespace = "IO"
}
```

```typescript
// /<PROJECT_ROOT_PATH>/index.ts
declare global {
  export namespace IO {
    ... type delcarations ...
  }
}
```

**Comment by arthurfiorette** [comment]
Hey, have you tried using `.prisma/client` as the output value?

**Comment by JayNakrani** [comment]
Yep, I did, and I got the same error: `Cannot find module '/<PROJECT_ROOT_PATH>/prisma/.prisma/client'`

**Comment by arthurfiorette** [comment]
```prisma
generator json_gen {
  provider = "prisma-json-types-generator"
  namespace = "IO"
  target = ".prisma/client"
}
```

**Comment by arthurfiorette** [comment]
Actually, it work work with .prisma because here is startsWith('.') and not startsWith('./') 🤡

**Comment by arthurfiorette** [comment]
@JayNakrani just released `1.1.2` with the fix, can you test it again?

**Comment by arthurfiorette** [comment]
Seems like that the `output` name is a dedicated keyword that works differently...

**Comment by JayNakrani** [comment]
Yep, 1.1.2 works great without `outputs` config. Thank you @arthurfiorette :raised_hands:

**Comment by arthurfiorette** [comment]
Haha, this PR might have been my fastest one. ⚡⚡⚡
