### ISSUE TITLE
Library is broken with 4.16.0

### ISSUE THREAD

**Issue by jakeleventhal** [arthurfiorette/prisma-json-types-generator#91]
https://github.com/prisma/prisma/issues/19863

**Comment by arthurfiorette** [comment]
Hey @jakeleventhal, thanks for your report, can you provide your prisma schema configuration? Like generators and preview features?

**Comment by arthurfiorette** [comment]
Hey @jakeleventhal, thanks for almost instantly reporting this bug after prisma 4.16.0 release! It's live at [v2.5.0](https://github.com/arthurfiorette/prisma-json-types-generator/releases/tag/v2.5.0)!
_Feel free to reopen this PR if needed :)_
