### ISSUE TITLE
[Docker] /bin/sh: 1: prisma-json-types-generator: not found

### ISSUE THREAD

**Issue by piotrkulpinski** [arthurfiorette/prisma-json-types-generator#97]
Hi, 
I'm having trouble generating prisma client inside Docker image.

I'm running a monorepo setup, with 2 apps using `database` package. 

`packages/database/package.json`

```json
{
  "dependencies": {
    "@prisma/client": "4.15.0"
  },
  "devDependencies": {
    "prisma": "4.15.0",
    "prisma-json-types-generator": "2.4.0"
  }
}
```

`packages/database/prisma/schema.prisma`

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "filteredRelationCount", "extendedWhereUnique"]
  binaryTargets   = ["native", "darwin-arm64"]
}

generator json {
  provider = "prisma-json-types-generator"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Site {
  id        String   @id @default(cuid())
  name      String
  slug      String   @unique @default("")
  /// [Settings]
  settings  Json     @default("{}")
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

`Dockerfile`
```dockerfile
# ...

FROM base AS production-deps
WORKDIR /app
RUN corepack enable
# ENV NODE_ENV production
RUN pnpm install --prod --no-frozen-lockfile
COPY --from=pruner /app/out/full/packages/database/prisma /app/packages/database/prisma
RUN pnpx prisma generate --schema /app/packages/database/prisma/schema.prisma

# ...
```

Error log:
```sh
#29 [production-deps 5/5] RUN pnpx prisma generate --schema /app/packages/database/prisma/schema.prisma
#29 1.350 .../.local/share/pnpm/store/v3/tmp/dlx-7 | Progress: resolved 1, reused 0, downloaded 0, added 0
#29 2.188 .../.local/share/pnpm/store/v3/tmp/dlx-7 |   +2 +
#29 2.256 .../dlx-7/node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
#29 2.352 .../.local/share/pnpm/store/v3/tmp/dlx-7 | Progress: resolved 2, reused 0, downloaded 2, added 2, done
#29 3.356 .../dlx-7/node_modules/@prisma/engines postinstall: Done
#29 3.709 .../v3/tmp/dlx-7/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
#29 3.787 .../v3/tmp/dlx-7/node_modules/prisma preinstall: Done
#29 6.295 Prisma schema loaded from packages/database/prisma/schema.prisma
#29 6.802 warn Preview feature "filteredRelationCount" is deprecated. The functionality can be used without specifying it as a preview feature.
#29 7.065 Error: Generator "prisma-json-types-generator" failed:
#29 7.065 
#29 7.065 /bin/sh: 1: prisma-json-types-generator: not found
#29 7.065 
#29 7.080  ERROR  Command failed with exit code 1: prisma generate --schema /app/packages/database/prisma/schema.prisma
```

Could be related to https://github.com/arthurfiorette/prisma-json-types-generator/issues/82 but I've tried removing `NODE_ENV` without any luck.

Is there anything I'm missing to make it work inside docker container? 
It's working locally without any issues.

**Comment by arthurfiorette** [comment]
You added `prisma-json-types-generator` as a development dependency and you're installing with `--prod`, which only installs dependencies from `dependencies` and not `devDependencies`. Move `prisma-json-types-generator` as a prod dependency and try again.

**Comment by piotrkulpinski** [comment]
Unfortunately, that's not it. I tried installing it as both dev and non-dev dependency but the error stays the same.

**Comment by arthurfiorette** [comment]
Well, the error says that the binary is not there, [we can see that it is in the package](https://www.npmjs.com/package/prisma-json-types-generator?activeTab=code), so you're not installing it inside your image.

You are using `pnpx` which links dependencies as if they were installed globally. Just change to `pnpm` and try again. Also, try placing it in your non-dev deps, run pnpm install to update your lockfile and remove the --prod and --no-frozen-lockfile from it.

**Comment by piotrkulpinski** [comment]
> You are using `pnpx` which links dependencies as if they were installed globally.

That was it, thanks!
